<?php get_header();
$img = get_template_directory_uri() . '/assets/images/';
$calendly = get_theme_mod('sf_calendly', 'https://calendly.com/sabrina-coolmindz/30min');
?>
<main id="top">
  <section class="hero">
    <div class="hero-copy">
      <p class="eyebrow">Leadership · Performance · Being Human</p>
      <h1 data-de="Klarheit für das, <em>was als Nächstes kommt.</em>" data-en="Clarity for <em>what comes next.</em>">Klarheit für das, <em>was als Nächstes kommt.</em></h1>
      <p class="hero-text" data-de="Mich interessieren die Momente, in denen die üblichen Antworten nicht mehr tragen. Wenn viel gesprochen, geplant und gearbeitet wird – aber zu wenig vorangeht." data-en="I am drawn to the moments when the usual answers stop working. When there is no shortage of conversation, planning or effort – yet too little is moving.">Mich interessieren die Momente, in denen die üblichen Antworten nicht mehr tragen. Wenn viel gesprochen, geplant und gearbeitet wird – aber zu wenig vorangeht.</p>
      <div class="hero-actions">
        <a class="button" href="<?php echo esc_url($calendly); ?>" target="_blank" rel="noreferrer" data-de="Gespräch beginnen <span>↗</span>" data-en="Start a conversation <span>↗</span>">Gespräch beginnen <span>↗</span></a>
        <a class="text-link" href="<?php echo esc_url(get_permalink(get_option('page_for_posts'))); ?>" data-de="Between Signals entdecken <span>↗</span>" data-en="Explore Between Signals <span>↗</span>">Between Signals entdecken <span>↗</span></a>
      </div>
    </div>
    <div class="hero-image-wrap"><img src="<?php echo esc_url($img . 'sabrina-hero.jpeg'); ?>" alt="Sabrina Fritzsche"><div class="signal-mark" aria-hidden="true"><i></i><i></i><i></i><i></i></div></div>
    <div class="hero-stamp" aria-hidden="true">BETWEEN<br>SIGNALS</div>
  </section>

  <section class="point-of-view" id="signals">
    <div class="section-number">01</div>
    <div class="pov-heading"><p class="eyebrow light">A point of view</p><h2 data-de="Die wichtigsten Signale sind selten <em>die lautesten.</em>" data-en="The most important signals are rarely <em>the loudest.</em>">Die wichtigsten Signale sind selten <em>die lautesten.</em></h2></div>
    <div class="pov-copy">
      <p data-de="Zwischen Kennzahlen und Gesprächen. Zwischen dem, was gesagt wird, und dem, was tatsächlich geschieht. Zwischen Leistung und Erschöpfung, Klarheit und Komplexität, Technologie und Menschsein." data-en="Between numbers and conversations. Between what is being said and what is actually happening. Between performance and exhaustion, clarity and complexity, technology and being human.">Zwischen Kennzahlen und Gesprächen. Zwischen dem, was gesagt wird, und dem, was tatsächlich geschieht. Zwischen Leistung und Erschöpfung, Klarheit und Komplexität, Technologie und Menschsein.</p>
      <p data-de="Ich erkenne schnell, was zusammengehört. Ich trenne Symptome vom eigentlichen Problem und bringe zur Sprache, was andere vielleicht bereits spüren, aber noch nicht klar benennen können." data-en="I see connections quickly. I separate symptoms from the real issue and put into words what others may already sense but cannot yet clearly name.">Ich erkenne schnell, was zusammengehört. Ich trenne Symptome vom eigentlichen Problem und bringe zur Sprache, was andere vielleicht bereits spüren, aber noch nicht klar benennen können.</p>
      <p class="pov-end" data-de="Das schafft Bewegung. Nicht immer bequem. Aber ehrlich, präzise und auf Wirkung ausgerichtet." data-en="That creates movement. Not always comfortable. But honest, precise and focused on impact.">Das schafft Bewegung. Nicht immer bequem. Aber ehrlich, präzise und auf Wirkung ausgerichtet.</p>
    </div><div class="orbit" aria-hidden="true"><span></span></div>
  </section>

  <section class="journal">
    <div class="journal-intro"><p class="eyebrow">The journal</p><h2 class="journal-title">Between Signals<span>.</span></h2><p class="journal-lead" data-de="Gedanken über Führung, Performance und das Menschsein in einer Welt, die immer schneller wird." data-en="Notes on leadership, performance and being human in a world that keeps accelerating.">Gedanken über Führung, Performance und das Menschsein in einer Welt, die immer schneller wird.</p><p data-de="Keine fertigen Wahrheiten. Keine schnellen Erfolgsrezepte. Sondern der Versuch, genauer hinzusehen: auf das, was uns antreibt, was uns zurückhält und was sich verändert, wenn wir beginnen, die richtigen Fragen zu stellen." data-en="No final truths. No shortcuts to success. Just an attempt to look more closely at what drives us, what holds us back and what changes when we begin asking better questions.">Keine fertigen Wahrheiten. Keine schnellen Erfolgsrezepte. Sondern der Versuch, genauer hinzusehen.</p></div>
    <div class="essay-list">
      <?php $q = new WP_Query(['posts_per_page'=>3]); if ($q->have_posts()): $i=1; while($q->have_posts()):$q->the_post(); ?>
        <a class="essay" href="<?php the_permalink(); ?>"><span class="essay-number"><?php echo esc_html(sprintf('%02d',$i)); ?></span><span class="essay-topic"><?php $cats=get_the_category(); echo esc_html($cats ? $cats[0]->name : 'Essay'); ?></span><strong><?php the_title(); ?></strong><span class="essay-arrow">↗</span></a>
      <?php $i++; endwhile; wp_reset_postdata(); else: ?>
        <?php foreach ([['Leadership','Was unklare Führung wirklich kostet'],['Performance','Leistung, ohne sich selbst zu verlieren'],['Perspective','Wenn mehr Einsatz nicht die Antwort ist']] as $i=>$item): ?>
          <a class="essay" href="<?php echo esc_url(get_permalink(get_option('page_for_posts'))); ?>"><span class="essay-number"><?php echo esc_html(sprintf('%02d',$i+1)); ?></span><span class="essay-topic"><?php echo esc_html($item[0]); ?></span><strong><?php echo esc_html($item[1]); ?></strong><span class="essay-arrow">↗</span></a>
        <?php endforeach; ?>
      <?php endif; ?>
    </div>
  </section>

  <section class="about" id="about">
    <div class="about-portrait"><img src="<?php echo esc_url($img . 'sabrina-portrait.jpeg'); ?>" alt="Portrait of Sabrina Fritzsche"><p data-de="Strategische Klarheit trifft menschliche Erfahrung." data-en="Strategic clarity meets human experience.">Strategische Klarheit trifft menschliche Erfahrung.</p></div>
    <div class="about-copy"><p class="eyebrow" data-de="Über mich" data-en="About">Über mich</p><h2 data-de="Ich bin Sabrina. <em>Ich mag Klarheit.</em>" data-en="I’m Sabrina. <em>I value clarity.</em>">Ich bin Sabrina. <em>Ich mag Klarheit.</em></h2><p data-de="Seit mehr als 15 Jahren arbeite ich in verantwortlichen Rollen an der Schnittstelle von Wachstum, Vertrieb, Marketing, Führung und Unternehmertum. Ich habe Teams aufgebaut, Veränderungen gestaltet und erlebt, wie unterschiedlich Strategie auf dem Papier und Realität im Unternehmen sein können." data-en="For more than 15 years, I have worked in leadership roles at the intersection of growth, sales, marketing and entrepreneurship. I have built teams, led through change and experienced the distance between strategy on paper and reality inside an organisation.">Seit mehr als 15 Jahren arbeite ich in verantwortlichen Rollen an der Schnittstelle von Wachstum, Vertrieb, Marketing, Führung und Unternehmertum.</p><p data-de="Meine Perspektive verbindet kommerzielle Erfahrung mit einem tiefen Interesse an Menschen: daran, wie wir entscheiden, führen, kommunizieren und unter Druck handlungsfähig bleiben." data-en="My perspective combines commercial experience with a deep interest in people: how we make decisions, lead, communicate and remain capable of acting under pressure.">Meine Perspektive verbindet kommerzielle Erfahrung mit einem tiefen Interesse an Menschen.</p><ul><li data-de="15+ Jahre Führung" data-en="15+ years in leadership">15+ Jahre Führung</li><li>Business &amp; Master Coach</li><li>Wim Hof Method Instructor</li><li>Operator at heart</li></ul></div>
  </section>

  <section class="experience"><p class="eyebrow" data-de="Ausgewählte Erfahrung" data-en="Selected experience">Ausgewählte Erfahrung</p><div class="logo-row"><div class="reference-logo logo-one"><span>1&amp;1</span></div><div class="reference-logo logo-everdrop">everdrop</div><div class="reference-logo logo-dustlight">Dustlight<i aria-hidden="true"><b></b><b></b><b></b></i></div><div class="reference-logo logo-anyever">ANY<span>EVER</span></div></div></section>

  <section class="work" id="work"><div class="work-image"><img src="<?php echo esc_url($img . 'sabrina-speaking.jpeg'); ?>" alt="Sabrina Fritzsche speaking on a panel"></div><div class="work-copy"><p class="eyebrow light">Work with me</p><h2 data-de="Manche Gedanken gehören gelesen. <em>Andere brauchen ein Gegenüber.</em>" data-en="Some thoughts are meant to be read. <em>Others need a counterpart.</em>">Manche Gedanken gehören gelesen. <em>Andere brauchen ein Gegenüber.</em></h2><p data-de="Ich arbeite ausgewählt mit Menschen und Organisationen, die bereit sind, genau hinzusehen – besonders dann, wenn eine Situation festgefahren ist, Entscheidungen schwerfallen oder die bisherigen Ansätze keine Wirkung mehr zeigen." data-en="I work selectively with people and organisations willing to look closely – particularly when a situation has stalled, decisions have become difficult or familiar approaches are no longer creating meaningful results.">Ich arbeite ausgewählt mit Menschen und Organisationen, die bereit sind, genau hinzusehen.</p><p class="formats">Strategic Sparring · Advisory · Executive Coaching · Workshops · Speaking</p><a class="button" href="<?php echo esc_url($calendly); ?>" target="_blank" rel="noreferrer" data-de="Gespräch beginnen <span>↗</span>" data-en="Start a conversation <span>↗</span>">Gespräch beginnen <span>↗</span></a></div></section>

  <section class="newsletter" id="newsletter"><div><p class="eyebrow">Letters from Between Signals</p><h2 data-de="Weniger Rauschen. Mehr Klarheit." data-en="Less noise. More clarity.">Weniger Rauschen. Mehr Klarheit.</h2></div><div><p data-de="Neue Essays über Führung, Performance, Technologie und Menschsein. Unregelmäßig. Persönlich." data-en="New essays on leadership, performance, technology and being human. Occasional. Personal.">Neue Essays über Führung, Performance, Technologie und Menschsein. Unregelmäßig. Persönlich.</p><?php $action=get_theme_mod('sf_newsletter',''); if($action): ?><form class="newsletter-form" action="<?php echo esc_url($action); ?>" method="post"><label class="screen-reader-text" for="sf-email">Email</label><input id="sf-email" type="email" name="email" required placeholder="Deine E-Mail-Adresse"><button type="submit">Abonnieren <span>↗</span></button></form><?php else: ?><a class="text-link" href="mailto:hello@sabrinafritzsche.com?subject=Between%20Signals" data-de="Interesse anmelden <span>↗</span>" data-en="Register interest <span>↗</span>">Interesse anmelden <span>↗</span></a><?php endif; ?></div></section>
</main>
<?php get_footer(); ?>
